<%@ Page Title="Contact" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Contact.aspx.cs" Inherits="Praca_Inżynierska.Contact" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div id="dvGrid" class="table" style="padding: 10px; width: 450px">
    <asp:GridView ID="GridView1" runat="server"  DataKeyNames="Id" AllowSorting="true" OnSorting="OnSorting"
    OnRowDeleting="OnRowDeleting" CssClass="table table-striped " EmptyDataText="No records has been added." AutoGenerateColumns="false"
     AutoGenerateDeleteButton="true">
        <Columns>
        <asp:BoundField DataField="Nazwa_Grupy" HeaderText="Grupa"  SortExpression="Nazwa_Grupy" />
        <asp:BoundField DataField="Nazwa_Przedmiotu" HeaderText="Przedmiot"  SortExpression="Nazwa_Przedmiotu" />
        <asp:BoundField DataField="ImieNazwisko" HeaderText="Nauczyciel"  SortExpression="ImieNazwisko" />
        <asp:BoundField DataField="typ_zajec" HeaderText="Typ zajęć" SortExpression="typ_zajec" />
        <asp:BoundField DataField="semestr" HeaderText="Semestr"  SortExpression="semestr" />
        <asp:BoundField DataField="ilosc_godzin" HeaderText="Ilość Godzin"  SortExpression="ilosc_godzin" />
    </Columns>
    </asp:GridView>
        </div>
</asp:Content>
